name: Postman Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Postman tests
        run: |
          docker run -v $(pwd):/etc/newman postman/newman:alpine run prueba.json
